module.exports = {
  SET_SEARCH_TEXT : "SET_SEARCH_TEXT",
  ADD_TODO : "ADD_TODO",
  TOGGLE_SHOW_COMPLETED : "TOGGLE_SHOW_COMPLETED",
  TOGGLE_TODO : "TOGGLE_TODO",
  START_ADD_TODO : "START_ADD_TODO",
  UPDATE_TODO : "UPDATE_TODO",
  ADD_TODOS : "ADD_TODOS",
  SHOW_MODAL : "SHOW_MODAL",
  HIDE_MODAL : "HIDE_MODAL"
}
